#!/usr/bin/env bash

: "${AEGIS_AWS_REGION:=ap-south-1}"
: "${AEGIS_HUB_CLUSTER_NAME:=AEGIS-EKS}"
: "${AEGIS_ARGOCD_NAMESPACE:=argocd}"
: "${AEGIS_ARGOCD_LOCAL_PORT:=8080}"
: "${AEGIS_ARGOCD_REMOTE_PORT:=443}"
: "${AEGIS_GRAFANA_NAMESPACE:=observability}"
: "${AEGIS_GRAFANA_LOCAL_PORT:=30080}"
: "${AEGIS_GRAFANA_REMOTE_PORT:=80}"
: "${AEGIS_GRAFANA_ADMIN_SECRET:=grafana-admin}"

: "${AEGIS_FACTORY_ID:=factory-a}"
: "${AEGIS_FACTORY_A_SSH_USER:=minsoo}"
: "${AEGIS_FACTORY_A_MASTER_HOST:=10.10.10.10}"

: "${AEGIS_IOT_THING_NAME_PREFIX:=AEGIS-IoTThing}"
: "${AEGIS_IOT_POLICY_NAME_PREFIX:=AEGIS-IoTPolicy}"
: "${AEGIS_IOT_TOPIC_ROOT:=aegis}"
: "${AEGIS_K8S_IOT_NAMESPACE:=ai-apps}"
: "${AEGIS_K8S_IOT_SECRET_PREFIX:=aws-iot}"
: "${AEGIS_K8S_IOT_SECRET_SUFFIX:=-cert}"

export AEGIS_AWS_REGION
export AEGIS_HUB_CLUSTER_NAME
export AEGIS_ARGOCD_NAMESPACE
export AEGIS_ARGOCD_LOCAL_PORT
export AEGIS_ARGOCD_REMOTE_PORT
export AEGIS_GRAFANA_NAMESPACE
export AEGIS_GRAFANA_LOCAL_PORT
export AEGIS_GRAFANA_REMOTE_PORT
export AEGIS_GRAFANA_ADMIN_SECRET
export AEGIS_FACTORY_ID
export AEGIS_FACTORY_A_SSH_USER
export AEGIS_FACTORY_A_MASTER_HOST
export AEGIS_IOT_THING_NAME_PREFIX
export AEGIS_IOT_POLICY_NAME_PREFIX
export AEGIS_IOT_TOPIC_ROOT
export AEGIS_K8S_IOT_NAMESPACE
export AEGIS_K8S_IOT_SECRET_PREFIX
export AEGIS_K8S_IOT_SECRET_SUFFIX
