#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# shellcheck disable=SC1091
source "${REPO_ROOT}/scripts/lib/config.sh"
aegis_load_config "${REPO_ROOT}"

REGION="${AWS_REGION:-${AEGIS_AWS_REGION}}"
CLUSTER_NAME="${CLUSTER_NAME:-${AEGIS_HUB_CLUSTER_NAME}}"
ARGOCD_NAMESPACE="${ARGOCD_NAMESPACE:-${AEGIS_ARGOCD_NAMESPACE}}"
GRAFANA_NAMESPACE="${GRAFANA_NAMESPACE:-${AEGIS_GRAFANA_NAMESPACE}}"
GRAFANA_SECRET_NAME="${GRAFANA_ADMIN_SECRET:-${AEGIS_GRAFANA_ADMIN_SECRET}}"
OUTPUT_FILE="${HUB_UI_CREDENTIALS_FILE:-${REPO_ROOT}/secret/hub-ui-credentials.txt}"
TERRAFORM_ROOT="${REPO_ROOT}/infra/hub"
OTP="${1:-}"

usage() {
  cat <<'USAGE'
Usage: scripts/ops/export-hub-ui-credentials.sh [MFA_OTP]

Writes Hub ArgoCD/Grafana login details to secret/hub-ui-credentials.txt.
The file is ignored by Git and written with 0600 permissions.
USAGE
}

if [[ "${OTP}" == "-h" || "${OTP}" == "--help" ]]; then
  usage
  exit 0
fi

# shellcheck disable=SC1091
source "${REPO_ROOT}/scripts/lib/aws-mfa.sh"
AWS_REGION="${REGION}" aegis_ensure_aws_mfa "${OTP}"
export AWS_REGION="${REGION}"
export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-${AWS_REGION}}"

aws eks update-kubeconfig --region "${REGION}" --name "${CLUSTER_NAME}" >/dev/null

read_secret_field() {
  local namespace="$1"
  local secret_name="$2"
  local field_name="$3"
  local encoded

  encoded="$(
    kubectl -n "${namespace}" get secret "${secret_name}" \
      -o "jsonpath={.data.${field_name}}" 2>/dev/null || true
  )"

  if [[ -z "${encoded}" ]]; then
    printf '%s' "unavailable"
    return 0
  fi

  printf '%s' "${encoded}" | base64 -d
}

terraform_output_raw() {
  local output_name="$1"
  terraform -chdir="${TERRAFORM_ROOT}" output -raw "${output_name}" 2>/dev/null || true
}

service_endpoint() {
  local namespace="$1"
  local name="$2"
  local protocol="$3"
  local ip hostname

  ip="$(kubectl -n "${namespace}" get svc "${name}" -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)"
  hostname="$(kubectl -n "${namespace}" get svc "${name}" -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)"

  if [[ -n "${ip}" ]]; then
    printf '%s://%s/' "${protocol}" "${ip}"
  elif [[ -n "${hostname}" ]]; then
    printf '%s://%s/' "${protocol}" "${hostname}"
  else
    printf '%s' "unavailable"
  fi
}

argocd_host="$(terraform_output_raw admin_ui_argocd_host)"
grafana_host="$(terraform_output_raw admin_ui_grafana_host)"
argocd_https_url="unavailable"
grafana_https_url="unavailable"

if [[ -n "${argocd_host}" ]]; then
  argocd_https_url="https://${argocd_host}"
fi

if [[ -n "${grafana_host}" ]]; then
  grafana_https_url="https://${grafana_host}"
fi

argocd_password="$(read_secret_field "${ARGOCD_NAMESPACE}" "argocd-initial-admin-secret" "password")"
grafana_username="$(read_secret_field "${GRAFANA_NAMESPACE}" "${GRAFANA_SECRET_NAME}" "admin-user")"
grafana_password="$(read_secret_field "${GRAFANA_NAMESPACE}" "${GRAFANA_SECRET_NAME}" "admin-password")"
argocd_tailscale_url="$(service_endpoint "${ARGOCD_NAMESPACE}" "argocd-server-tailscale" "https")"
grafana_tailscale_url="$(service_endpoint "${GRAFANA_NAMESPACE}" "grafana-tailscale" "http")"

mkdir -p "$(dirname "${OUTPUT_FILE}")"
chmod 700 "${REPO_ROOT}/secret" "$(dirname "${OUTPUT_FILE}")"

tmp_file="$(mktemp "${OUTPUT_FILE}.tmp.XXXXXX")"
chmod 600 "${tmp_file}"

cat >"${tmp_file}" <<EOF
# Generated by scripts/ops/export-hub-ui-credentials.sh
# This file is ignored by Git via secret/.
# Do not commit or paste these values into docs, issues, or logs.

generated_at_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)
cluster_name=${CLUSTER_NAME}
region=${REGION}

[argocd]
namespace=${ARGOCD_NAMESPACE}
url=${argocd_https_url}
tailscale_url=${argocd_tailscale_url}
username=admin
initial_admin_password=${argocd_password}

[grafana]
namespace=${GRAFANA_NAMESPACE}
url=${grafana_https_url}
tailscale_url=${grafana_tailscale_url}
username=${grafana_username}
admin_password=${grafana_password}
EOF

mv "${tmp_file}" "${OUTPUT_FILE}"
chmod 600 "${OUTPUT_FILE}"

echo "Hub UI credentials written to ${OUTPUT_FILE}"
